# Generated by Django 4.0.1 on 2022-01-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlist',
            options={'verbose_name_plural': 'waitlist entiries'},
        ),
        migrations.RenameField(
            model_name='waitlist',
            old_name='description',
            new_name='email',
        ),
    ]
