# Generated by Django 4.0.1 on 2022-01-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_alter_waitlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Class Level'),
        ),
    ]
